<?xml version="1.0"?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  name="simple_arm">
  <gazebo>
    <plugin filename="libign_ros2_control-system.so" name="ign_ros2_control::IgnitionROS2ControlPlugin">
      <parameters>$(find simple_arm_camera)/config/simple_arm_controllers.yaml </parameters>
    </plugin>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <robot_sim_type>gazebo_ros2_control/GazeboSystem</robot_sim_type>
      <parameters>$(find simple_arm_camera)/config/simple_arm_controllers.yaml</parameters>
    </plugin>
    <plugin
      filename="ignition-gazebo-sensors-system"
      name="ignition::gazebo::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin
      filename="ignition-gazebo-scene-broadcaster-system"
      name="ignition::gazebo::systems::SceneBroadcaster">
    </plugin>
  </gazebo>

  <ros2_control name="simple_arm_ros2_control" type="system">
    <hardware>
      <plugin>ign_ros2_control/IgnitionSystem</plugin>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>
    <joint name="joint1">
      <command_interface name="position">
        <param name="min">-2</param>
        <param name="max">2</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="joint2">
      <command_interface name="position">
        <param name="min">-2</param>
        <param name="max">2</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="joint3">
      <command_interface name="position">
        <param name="min">-2</param>
        <param name="max">2</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

  <xacro:property name="mass" value="1"/>
  <xacro:property name="width" value="0.1"/>
  <xacro:property name="height" value="1"/>
  <xacro:property name="height_link1" value="${height*2}"/>

  <link name="world"/>

  <joint name="fixed_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link"/>

  <joint name="joint0" type="fixed">
    <parent link="base_link"/>
    <child link="link0"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="link0">
    <visual>
      <geometry>
        <box size="${width} ${width} ${width}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${width/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (width*width + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="link0"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0" upper="1.6" lower="-1.6"/>
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="0 0 ${height_link1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height_link1}"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + height_link1*height_link1)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (height_link1*height_link1 + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${height_link1}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0" upper="1.6" lower="-1.6"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (height*height + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0" upper="1.6" lower="-1.6"/>
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (height*height + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="tool_joint" type="fixed">
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="tool_link"/>
  </joint>

  <link name="tool_link">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 -1.57 1.57"/>
    <parent link="tool_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0.03" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.0.5"/>
      </geometry>
    </visual>
    <material name="gray"/>
  </link>

  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical"></link>

  <gazebo reference="camera_link">
    <sensor name="camera_link" type="camera">
      <update_rate>10.0</update_rate>
      <always_on>true</always_on>
      <ignition_frame_id>camera_link</ignition_frame_id>
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <topic>/image_raw</topic>
      <camera name="camera">
        <horizontal_fov>1.3</horizontal_fov>
        <image>
          <width>600</width>
          <height>600</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

</robot>
